-- 애플리케이션의 ddl-auto=update가 같은 테이블을 생성한다.
-- 자동 DDL을 끈 환경에서는 백엔드 배포 전에 실행한다.
CREATE TABLE IF NOT EXISTS course_member_revocations (
    course_member_revocation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    revoked_through_invite_id BIGINT NOT NULL,
    CONSTRAINT uq_course_member_revocations_course_user UNIQUE (course_id, user_id)
);
